### ISSUE TITLE
Improve class agimus_sot.tools.Manifold

### ISSUE THREAD

**Issue by florent-lamiraux** [agimus/agimus-sot#11]
This class seems to be wrapper to a task in the Stack of Tasks.
* I propose to rename it `Task`.

It seems that member `constraints` is not used
* I propose to remove it.

It seems that member `tasks` is a list with only one element
* I propose to store the element in the member without a list.

Member `topics` is not clear to me. Maybe an example would make it clearer.

**Comment by jmirabel** [comment]
>   * I propose to rename it `Task`.

Agreed.

> It seems that member `constraints` is not used
> 
>     * I propose to remove it.
> 
Agreed.

> It seems that member `tasks` is a list with only one element

This is true only for derived class. However, operation `Manifold + Manifold` returns a `Manifold` with several tasks.

> 
> Member `topics` is not clear to me. Maybe an example would make it clearer.

Could be renamed into something that means *desired references to be provided to this `Manifold`*. At the moment, `topics` contains a dictionary of dictionaries. It could be replaced by a dictionary of instances of a class (maybe `ExternalReference` or `ExternalSignal` ?).
A class would also put into one place the topic definition and the topic handler (currently at the end of file src/agimus_sot/supervisor.py).
