### ISSUE TITLE
Factory fails to initialize

### ISSUE THREAD

**Issue by florent-lamiraux** [agimus/agimus-sot#20]
@jmirabel : in commit cf399987, you changed the prototype of OpFrame:
https://github.com/agimus/agimus-sot/blob/7d64cd54fda48c6afa09d7c499c51285931cc902/src/agimus_sot/task/op_frame.py#L39

Now, launching Pyrene demo in simulation raises an error
```
[ERROR] [1590680835.927356]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 37, in makeSupervisorWithFactory
  File "/home/florent/devel/pyrene/install/lib/python2.7/dist-packages/agimus_sot/factory.py", line 541, in setupContactFrames
    self.contactFrames [name] = OpFrame(res)
TypeError: __init__() takes at least 3 arguments (2 given)
```
Do you have local modifications in your code ?

**Comment by jmirabel** [comment]
b811ad2 should fix this. I haven't tried this demo for some time.

**Comment by florent-lamiraux** [comment]
Thank you.
